import Script from "next/script";
import { Inter } from "next/font/google";

import Header from "./layout/header-layout";
import Footer from "./layout/footer-layout";

import "./layout/header-layout/header.scss";
import "@/scss/globals.scss";
import "@/scss/button.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "BDAO",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <Script
                    src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.0.1/model-viewer.min.js"
                    type="module"
                />
            </head>

            <body className={inter.className}>
                <Header />

                <div className="main-bg">
                    <div className="bg-texture">
                        <section className="pt-[81px]"></section>
                        {children}
                    </div>
                </div>
                <Footer />
            </body>
        </html>
    );
}
